title: Nava Rastegar # your name (or website title) here
logo: "images/Nava%20Pick%203.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student at the University of Maryland, Baltimore County. Researching the potential uses of spiderwebs as citizen-science air pollution monitors with Drs. Chris Hawn and Dillon Mahmoudi.
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
